spring:
  cloud:
    gateway:
      routes:
        - id: auth_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
#          filters:
#            - JwtDecodeFilter
        - id: channel_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/channels/**
          filters:
            - JwtDecodeFilter
        - id: key_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/key/**
          filters:
            - JwtDecodeFilter
        - id: hist_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/hist/**
          filters:
            - JwtDecodeFilter
        - id: alarm_route
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/alarm/**
        - id: html_route
          uri: http://localhost:3000
          predicates:
            - Path=/api/v1/alarm/**

logging:
  level:
    root: INFO

jwt:
  secret: "${random.value}${random.value}"
  expire-day: 30

security:
  allowed-origins:
    http://localhost:5500,
    http://127.0.0.1:5500,
    https://k8a407.p.ssafy.io

server:
  max-http-header-size: 16384

