spring:
  cloud:
    gateway:
      routes:
        - id: auth_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v2/auth/**
        - id: jwt_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v2/channels/**, /api/v2/key/**, /api/v2/member/**
          filters:
            - JwtDecodeFilter
        - id: hist_route
          uri: http://localhost:8083
          predicates:
            - Path=/api/v2/history/**
          filters:
            - JwtDecodeFilter
        - id: alarm_route
          uri: http://localhost:8084
          predicates:
            - Path=/api/v2/alarm/**


jwt:
  secret: "kSHg+dcLWjK1JwiS9bttxEMpkMc8+/c+5ca5w5R5R5g="
  expire-day: 30

security:
  allowed-origins:
    http://localhost:5500,
    http://127.0.0.1:5500,
    https://k8a407.p.ssafy.io

server:
  max-http-header-size: 16384

crypto:
  secret: it's secret
  salt: bf53862cfb2b0148

logging:
  level:
    root: trace