spring:
  cloud:
    gateway:
      routes:
        - id: auth_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: channel_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/channel/**
        - id: key_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/key/**
        - id: hist_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/hist/**
        - id: alarm_route
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/alarm/**
        - id: html_route
          uri: http://localhost:3000
          predicates:
            - Path=
server:
  max-http-header-size: 16384

