server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3306/moalarm

  jpa:
    generate-ddl: true

crypto:
  secret: it's secret
  salt: bf53862cfb2b0148

jwt:
  secret: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  expire-day: 30
