spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/moalarm
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: "test"
      username: root
      password: 1234

jwt:
  secret: "${random.value}${random.value}"
  expire-day: 30

mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    ssl:
      checkServerIdentity: true

crypto:
  secret: it's secret
  salt: bf53862cfb2b0148